-- MySQL Script generated by MySQL Workbench
-- Wed Apr 27 10:03:26 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema DB_Blog_Pessoal
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema DB_Blog_Pessoal
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DB_Blog_Pessoal` DEFAULT CHARACTER SET utf8 ;
USE `DB_Blog_Pessoal` ;

-- -----------------------------------------------------
-- Table `DB_Blog_Pessoal`.`TB_Tema`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DB_Blog_Pessoal`.`TB_Tema` ;

CREATE TABLE IF NOT EXISTS `DB_Blog_Pessoal`.`TB_Tema` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `Descricao` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_Blog_Pessoal`.`TB_Usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DB_Blog_Pessoal`.`TB_Usuarios` ;

CREATE TABLE IF NOT EXISTS `DB_Blog_Pessoal`.`TB_Usuarios` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(255) NOT NULL,
  `Usuario` VARCHAR(255) NOT NULL,
  `Senha` VARCHAR(255) NOT NULL,
  `Foto` VARCHAR(255) NULL,
  `Tipo` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_Blog_Pessoal`.`TB_Postagem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DB_Blog_Pessoal`.`TB_Postagem` ;

CREATE TABLE IF NOT EXISTS `DB_Blog_Pessoal`.`TB_Postagem` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `Titulo` VARCHAR(255) NOT NULL,
  `Texto` VARCHAR(255) NOT NULL,
  `data` DATETIME NULL,
  `TB_Tema_id` BIGINT NOT NULL,
  `TB_Usuarios_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`, `TB_Tema_id`, `TB_Usuarios_id`),
  INDEX `fk_TB_Postagem_TB_Tema_idx` (`TB_Tema_id` ASC) VISIBLE,
  INDEX `fk_TB_Postagem_TB_Usuarios1_idx` (`TB_Usuarios_id` ASC) VISIBLE,
  CONSTRAINT `fk_TB_Postagem_TB_Tema`
    FOREIGN KEY (`TB_Tema_id`)
    REFERENCES `DB_Blog_Pessoal`.`TB_Tema` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TB_Postagem_TB_Usuarios1`
    FOREIGN KEY (`TB_Usuarios_id`)
    REFERENCES `DB_Blog_Pessoal`.`TB_Usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
